---
  - name: Install additional OS packages
    become: yes
    yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
    with_items:
      - php-mbstring
      - java-1.8.0-openjdk-headless
      - xorg-x11-server-Xvfb-1.17.4-9.5.el6.centos
      - firefox-45.4.0-1.el6.centos
      - xorg-x11-server-Xorg-1.17.4-9.5.el6.centos
      - libXfont-1.5.1-2.el6.x86_64

  - name: Create behat install directory
    become: yes
    file:
        path: "/opt/behat"
        owner: root
        group: root
        state: directory
        follow: yes

  - name: Create composer file for behat installation
    become: yes
    template:
        src: "behat.composer.json.j2"
        dest: "/opt/behat/composer.json"
        force: yes

  - name: Remove existing lock file
    become: yes
    file:
        path: "/opt/behat/composer.lock"
        state: absent

  - name: Install behat via composer
    become: yes
    shell: "/usr/local/bin/composer install --no-interaction"
    args:
        chdir: "/opt/behat"

  - name: Link behat command
    become: yes
    file:
        src: "/opt/behat/bin/behat"
        dest: "/usr/bin/behat"
        state: link


  - name: Create selenium directory
    become: yes
    file:
        path: "/opt/selenium"
        owner: root
        group: root
        state: directory
        follow: yes

  - name: Download selenium
    become: yes
    get_url:
      url: "http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
      dest: "/opt/selenium/selenium-server-standalone-2.53.1.jar"
      force: no
      timeout: 400

  - name: Copy PAM environmental variables.
    become: yes
    template:
      src: "pam_env.conf"
      dest: "/etc/security/pam_env.conf"

  - name: Copy selenium init script.
    become: yes
    copy:
      src: "selenium.init.d"
      dest: "/etc/init.d/selenium"
      mode: 0755

  - name: Copy xvfb init script.
    become: yes
    copy:
      src: "xvfb.init.d"
      dest: "/etc/init.d/xvfb"
      mode: 0755

  - name: Ensure Selenium is started and enabled on boot.
    service:
        name: selenium
        state: started
        enabled: yes
