$ANSIBLE_VAULT;1.1;AES256
61313764316238323535393532333061303164333339613138333338613961366533353265663462
6566366534613766373630313136373362333364316366630a626361303233353833653530613162
37623031393139336461356135363465383234393130363131366138313633303866626534396336
6636636134323561310a386138663563396432333264396366663435313935656539373865613864
39636162333137353936633235366632333564633932623262366438333936366237323538343038
65366165336332393966346165343864363330356334633561333137616562666562623033306563
64626563376138316539653634623937363862326432353632343630636539306533393233383262
37616565323234633138663131396136326237343337313765353366353632616464653037346362
61383563393235383963376438313462346632653032363639343430393261323130303330366263
61356430336164333235346439623164363663353466643765373762616363383562303432366339
30666136636431363837653631363837633164333137346432393034393339633533343137663537
61356362366333323031
