- hosts: 127.0.0.1

  vars_prompt:
    - name: "force"
      prompt: "Would you like to force a complete rebuild? [Y/N] This will destory any local modifications to any associated repositories."
      private: no

  connection: local

  tasks:
    - name: Reset repositories
      when: force == "Y" or force == "y" or force == "Yes" or force == "yes"
      command: "git reset --hard origin/{{ item.branch }}"
      args:
        chdir: "{{ item.path }}"
      with_items:
          - { path: "~/express_local/data/code/varnish", branch: "master"}
          - { path: "~/express_local/data/code/atlas", branch: "master"}

    - name: Fetch the repositories
      command: "git fetch"
      args:
          chdir: "{{ item.path }}"
      with_items:
          - { path: "~/express_local/data/code/varnish"}
          - { path: "~/express_local/data/code/atlas"}
          - { path: "~/express_local/data/code/logstash"}

    - name: Checkout the correct branches
      command: "git checkout {{ item.branch }}"
      args:
          chdir: "{{ item.path }}"
      with_items:
          - { path: "~/express_local/data/code/varnish", branch: "master"}
          - { path: "~/express_local/data/code/atlas", branch: "master"}

    - name: Pull the repositories
      command: "git pull"
      args:
          chdir: "{{ item.path }}"
      with_items:
          - { path: "~/express_local/data/code/varnish"}
          - { path: "~/express_local/data/code/atlas"}
