---
  # This playbook will be run on webservers for the Inventory.
  - hosts: inventory
    become: yes
    vars:
        express_code_varnish: false
        express_code_elk: false
        express_code_logstash: false
        express_code_logstash_shipper: true
    roles:
      - {role: ssh_keys, key_set: 'user' }
      - {role: server_base }
      - {role: apache_inventory }
      - {role: python }
      - {role: logstash }
      - {role: ssh_keys, key_set: 'dplagnt_src' }
    vars:
      python_location: /home/dplagnt/inventory-python27-environment
